#!/usr/bin/env bash
currentDir=$(pwd)

#================================================================
#region Functions

Exit(){
    cd "$currentDir"
    exit 1
}

Print(){
    echo -e "\033[0;34mgit-mirror_tracker\033[0m: $1"
}

#endregion

#================================================================
#region Repository

#check if repo exists
repoDir="$HOME"/.config/git-mirror_tracker/
if [ ! -d "$repoDir".git  ]; then
    Print "Initializing git-mirror_tracker repository at $repoDir"
    mkdir -p "$repoDir"
    git init "$repoDir"
fi

#----------------------------------------------------------------
#Functions

RepoUpdate(){   #fileName #config
    Print "Saving local config for $1"
    echo "$2" > "$repoDir$1"
}

RepoCommit(){
    cd "$repoDir"
    #check changes
    if [ -z "$(git status --porcelain)" ]; then
        Print "Repo has no changes"
        return
    else
        Print "Repo has changes"
        git status
    fi
    #commit
    commitCount="$(git rev-list --count HEAD)"
    if [ -z $commitCount ]; then
        commitName="First Commit"
    else
        commitName="Update $commitCount"
    fi
    Print "Commiting \"$commitName\""
    git add *
    git commit -m "$commitName"
}

RepoStage(){
    cd "$repoDir"
    git add *
}

#endregion

#================================================================
#get base dir

Update(){
    #check baseDir
    if [ -z "$1" ]; then
        baseDir="$HOME"
    else
        baseDir="$1"
    fi

    #search
    for dir in "$baseDir"/*; do
        if [ -d "$dir/.git" ]; then
            #echo "Git repository found: $dir"
            #scope
            cd "$dir"
            #git config --local --list
            RepoUpdate "${dir:${#baseDir} + 1}" "$(git config --local --list)"
            #echo $(git remote -v)
        fi
    done

    #stage
    RepoStage
}

#================================================================
#region Commands

case "$1" in
    #------------------------------------------------------------
    log)
        cd "$repoDir"
        git log
        ;;
    status)
        cd "$repoDir"
        git status
        ;;
    commit)
        RepoCommit
        ;;
    stage)
        Update
        ;;
    reset)
        cd "$repoDir"
        git reset --hard
        ;;
    #------------------------------------------------------------
    update)
        Update
        RepoCommit
        ;;
    #------------------------------------------------------------
    *)
        Print "No command"
        ;;
esac

#endregion

#================================================================
#region Exit

Exit

#endregion